export * from '../capture/model/capture'
export * from '../pessoa/model/person-model'
export * from '../processo/model/process'
export * from '../propostal/model/proposal'
export * from './default-records'
